name: appointemnt
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.3.0
  flutter_native_splash: ^2.4.7
  dio: ^5.10.0
  json_annotation: ^4.12.0
  freezed: ^3.2.5
  retrofit: ^4.9.0
  logger: ^2.6.0  # for logging purpose
  pretty_dio_logger: ^1.4.0
  flutter_bloc: ^9.1.1
  get_it: ^8.0.2
  custom_form_w: ^2.0.8



  



   

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^10.0.1
  json_serializable: ^6.14.0
  build_runner: ^2.15.1


    
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
   - assets/images/
   - assets/svgs/
